### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by pandon101** [Jericho1060/du-storage-monitoring#9]
First off, I like your script. It's small and easy to setup.

I would like to see groups. Maybe:  
<prefix>_<itemId>_<containserSize>_<amountOfContainers>_<GroupName>

This would let us Group Pures, Ore and Products separately or even By Tier. 

This could reduce number of screens you use. 

You could do a <GroupID> but <GroupName> would let you do Subtitles (if enabled)

Just A feature request. Thanks for your time.

**Comment by thoda-dev** [comment]
Hi, I'm not sure to understand the need

You can put a new title on screens you can stack or not same resources

If you want to split one screen on several groups, this is not planned for now and could cause an issue due to a limitation on how much data I can send on a screen (game limit)

**Comment by thoda-dev** [comment]
just to add a remark, the game data for items do not give us a "group" for each item

**Comment by thoda-dev** [comment]
Closing as not receding answer
